---
version: "3.7"

services:
  install_site:
    image: git.maby.dev/organization/install_site:0.1.0
    ports:
      - "80:80"
    environment:
      - BASE_URL=$BASE_URL
      - EMAIL=$EMAIL
    volumes:
      - ./nginx.conf:/web/element.conf
      - sites-availables:/sites-availables/
      - certs:/etc/letsencrypt/

  element:
    image: vectorim/element-web
    restart: unless-stopped
    user: :$PUID:$PGID"
    volumes:
      - config:/app/config.json
    networks:
      - default
      - selfhost

volumes:
  config:
  sites-availables:
    external: true
  certs:
    external: true

networks:
  default:
  selfhost:
    external: true
